# 어제 복습문제 풀이

## 문제 1: 이메일 주소 변경하기 (sub 사용)
문제: 주어진 문자열에서 모든 이메일 주소를 user@weniv.co.kr으로 변경하시오.

예시 입력: "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
예시 출력: "저의 이메일 주소는 kim123@weniv.co.kr입니다. 친구의 이메일 주소는 lee456@weniv.co.kr입니다."

힌트: 이메일 주소를 찾기 위한 정규표현식은 \b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b를 사용할 수 있습니다.

In [ ]:
# 풀이 1
def solution(url):
    return url.split('@')[0] + '@weniv.co.kr'

solution('user@weniv.co.kr')

'user@weniv.co.kr'

In [ ]:
# 풀이 2
import re # import 와 코드는 보통 2칸 띄우기


def chagedomain(url):
    return url.split('@')[0]+'@weniv.co.kr'

findpattern = re.findall(r"[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}",
                        "저의 이메일 주소는 kim123@gmail.com입니다."
                        "친구의 이메일 주소는 lee456@gmail.com입니다.")

for url in findpattern:
    print(chagedomain(url))

kim123@weniv.co.kr
lee456@weniv.co.kr


In [ ]:
# 출제 했던 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"[a-zA-Z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}", "user@weniv.co.kr", my_string)

'저의 이메일 주소는 user@weniv.co.kr입니다. 친구의 이메일 주소는 user@weniv.co.kr입니다.'

In [ ]:
# 변경된 문제의 해답
my_string = "저의 이메일 주소는 kim123@gmail.com입니다. 친구의 이메일 주소는 lee456@gmail.com입니다."
re.sub(r"@[a-zA-Z0-9.-]+\.[A-Z|a-z]{2,}", "@weniv.co.kr", my_string)

'저의 이메일 주소는 kim123@weniv.co.kr입니다. 친구의 이메일 주소는 lee456@weniv.co.kr입니다.'

## 문제 2: HTML 태그 제거하기 (sub 사용)
문제: 주어진 HTML 문자열에서 모든 HTML 태그를 제거하고 텍스트만 남기시오.
```
예시 입력: "<p>이것은 <b>예시</b> 문장입니다.</p>"
예시 출력: "이것은 예시 문장입니다."
```
힌트: HTML 태그를 찾기 위한 정규표현식은 <[^>]+>를 사용할 수 있습니다.

In [ ]:
# 작은 따옴표 3개도 f-string을 사용할 수 있다.

# 기본 역량 풀이 20문제(프로그래머스 10

* 코딩 인터뷰 완전분석
* 듣기
* 예제
* 무식하게 풀기
* 최적화
* 검토하기
* 구현하기
* 테스트

In [ ]:
# 문제1
'''
정수가 담긴 리스트 num_list가 주어질 때, num_list의 원소 중 짝수와 홀수의
개수를 담은 배열을 return 하도록 solution 함수를 완성해보세요.
1 ≤ num_list의 길이 ≤ 100
0 ≤ num_list의 원소 ≤ 1,000
'''

def solution(data):
    홀수 = [i % 2 != 0 for i in data]
    짝수 = [i % 2 == 0 for i in data]
    print(홀수, 짝수)
    return data

solution([1, 2, 3, 4, 5])

[True, False, True, False, True] [False, True, False, True, False]


[1, 2, 3, 4, 5]

In [ ]:
def solution(num_list):
    answer = [0, 0]
    for i in num_list:
        answer[i % 2] += 1
    return answer

In [ ]:
def solution(data):
    count = 0
    for i in data:
        if i % 2 == 0:
            count += 1
    return [count, len(data)-count]

In [ ]:
# 좋은 풀이는 아닙니다.
# data의 가변 최대치를 봅니다.
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    return [sum(짝수), len(data) - sum(짝수)] # sum이 순회합니다.

In [ ]:
def solution(data):
    짝수 = [i % 2 == 0 for i in data]
    갯수 = sum(짝수)
    return [갯수, len(data) - 갯수]

In [ ]:
# 문제2 머쓱이 키비교
'''
머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다.
머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가
매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록
solution 함수를 완성해보세요.
제한사항
1 ≤ array의 길이 ≤ 100
1 ≤ height ≤ 200
1 ≤ array의 원소 ≤ 200
'''
def solution(array, height):
    count = 0
    for i in array:
        if i > height:
            count += 1
    return count


solution([149, 180, 192, 170], 167)

3

In [ ]:
def solution(array, height):
    print(list(filter(lambda x: x > height, array)))
    return

solution([149, 180, 192, 170], 167)

[180, 192, 170]


In [ ]:
# filter에는 len가 없음.
# filter은 순회 돌기전까지 실행이 되지 않는 함수
# 순회를 돌아야 각 원소 별로 접근 가능
def solution(array, height):
    return len((list(filter(lambda x: x > height, array))))

solution([149, 180, 192, 170], 167)

3

In [ ]:
def solution(array, height):
    return sum(map(lambda x: x > height, array))

solution([149, 180, 192, 170], 167)

In [ ]:
# 언패킹해서 사용할 수 잇는 것들은 언패킹으로 사용하는 것이 좋음 -> 가독성이 좋아짐
def solution(date):
    array, height = date
    pass


solution([149, 180, 192, 170], 167)

TypeError: solution() takes 1 positional argument but 2 were given

In [ ]:
# 문제 3
'''
문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의
합을 return하도록 solution 함수를 완성해주세요.
제한사항
1 ≤ my_string의 길이 ≤ 1,000
my_string은 소문자, 대문자 그리고 한자리 자연수로만 구성되어있습니다.
'''

def solution(my_string):
    result = 0
    for i in my_string:
        if i.isdigit():
            result += int(i)

    return result

solution("aAb1B2cC34oOp")

10

In [ ]:
# 비효율적이지만 문법복습차원
def solution(my_string):
    return list((filter(lambda x: x.isdigit(), list(my_string))))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# 비효율적이지만 문법복습차원
def solution(my_string):
    return list((filter(str.isdigit, list(my_string))))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# 비효율적이지만 문법복습차원
def solution(my_string):
    return list((filter(str.isdigit, my_string)))

solution("aAb1B2cC34oOp")

['1', '2', '3', '4']

In [ ]:
# 효율적이진 않지만, 문법 복습차원에서
def solution(my_string):
    return sum(map(int,(filter(str.isdigit, my_string))))

solution("aAb1B2cC34oOp")

10

In [ ]:
# r은 raw 날것의 라는 뜻이 있음.
# raw data는 가공되지 않은 순수 데이터
import re

def solution(s):
    return sum(map(int, re.findall(r'[0-9]', s)))

solution('aAb1B2cC34oOp')

10

In [ ]:
import re

def solution(s):
    return sum(map(int, (re.sub(r'[a-zA-Z]', '', s))))

solution('aAb1B2cC34oOp')

10

In [ ]:
# 문제4 암호해독
'''
군 전략가 머쓱이는 전쟁 중 적군이 다음과 같은 암호 체계를
사용한다는 것을 알아냈습니다.

암호화된 문자열 cipher를 주고받습니다.
그 문자열에서 code의 배수 번째 글자만 진짜 암호입니다.
문자열 cipher와 정수 code가 매개변수로 주어질 때 해독된
암호 문자열을 return하도록 solution 함수를 완성해주세요.
'''

def solution(cipher, code):
    return cipher[code-1::code]

solution("dfjardstddetckdaccccdegk", 4)

'attack'

In [ ]:
def solution(cipher, code):
    count = 1
    for i in cipher:
        if count == code:
            print(i)
            count = 0
        count += 1

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
def solution(cipher, code):
    count = 1
    for i, j in enumerate(cipher, 1):
        if i % code == 0:
            print(j)

solution("dfjardstddetckdaccccdegk", 4)

a
t
t
a
c
k


In [ ]:
#  문제 5 369게임
'''
머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며
3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다.
머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수
횟수를 return 하도록 solution 함수를 완성해보세요.
'''

def solution(order):
    order = str(order)
    return order.count('3') + order.count('6') + order.count('9')

solution('29423')

2

In [ ]:
import re


re.findall(r'[369]','12312315923879456')

['3', '3', '9', '3', '9', '6']

In [ ]:
import re

def solution(order):
    order = str(order)
    return len(list(re.findall(r'[369]', order)))


solution('1238463989541638456')


8

In [ ]:
# 문제 6 중복문자 제거
'''
문자열 my_string이 매개변수로 주어집니다. my_string에서 중복된 문자를
제거하고 하나의 문자만 남긴 문자열을 return하도록 solution 함수를 완성해주세요.
제한사항
1 ≤ my_string ≤ 110
my_string은 대문자, 소문자, 공백으로 구성되어 있습니다.
대문자와 소문자를 구분합니다.
공백(" ")도 하나의 문자로 구분합니다.
중복된 문자 중 가장 앞에 있는 문자를 남깁니다.
'''

def solution(s):
    answer = ''
    for i in s:
        if i not in answer:
            answer += i
    return answer

solution('people')

'peol'

In [ ]:
def solution(s):
    return ''.join(dict.fromkeys(s)) # 딕셔너리는 키의 중복이 안된다는 점을 이용, 3.6버전부터 순서 보장

solution('people')

'peol'

In [ ]:
# 문제 7 A로 B만들기
'''
문자열 before와 after가 매개변수로 주어질 때, before의 순서를 바꾸어
after를 만들 수 있으면 1을, 만들 수 없으면 0을 return 하도록 solution
함수를 완성해보세요.
제한사항
0 < before의 길이 == after의 길이 < 1,000
before와 after는 모두 소문자로 이루어져 있습니다.

'''

def solution(before, after):
    if len(before) != len(after):
        return 0
    elif before[::-1] == after:
        return 1
    else:
        return 0

solution("olleh", "hello")

1

In [ ]:
solution("allpe", "apple")

0

In [ ]:
def solution(before, after):
    # 예외 처리는 앞에서 반드시 잡아야함. 특히 요소가 없거나 길이가 0인 경우
    if len(before) != len(after):
        return 0
    return 1 if sorted(before) == sorted(after) else 0



solution("olleh", "hello")
solution("allpe", "apple")

0

In [ ]:
import collections

collections.Counter("olleh")
collections.Counter("olleh") == collections.Counter("hello")
collections.Counter("olleh") == collections.Counter("hhhhhhhhhello")

False

In [ ]:
def solution(before, after):
    b = list(before)
    a = list(after)
    for i in b:
        if i in a:
            print(a)
            a.remove(i)
        else:
            return 0
    if a:
        return 0
    return 1

solution("olleh", "hello")

['h', 'e', 'l', 'l', 'o']
['h', 'e', 'l', 'l']
['h', 'e', 'l']
['h', 'e']
['h']


1

In [ ]:
# 회문

# 'hello' => 'elloh' => 'llohe'
# 'hello' => 'ohell' => 'lohel'
# collections.deque를 사용해서 풀면 쉽게 풀립니다.

# 문제1 'hello'를 앞뒤로 이동시켜 'llohe'를 만들 수 있나요?
# 'hellohello'

# 문제2 몇칸 이동했나요?
# 'hellohello'.index('llohe')

In [ ]:
# 문제 8 저주의 숫자 3
'''
3x 마을 사람들은 3을 저주의 숫자라고 생각하기 때문에 3의 배수와 숫자 3을 사용하지 않습니다.
3x 마을 사람들의 숫자는 다음과 같습니다.

10진법	3x 마을에서 쓰는 숫자	10진법	3x 마을에서 쓰는 숫자
1	               1	           6	         8
2	               2	           7	         10
3	               4	           8	         11
4	               5	           9	         14
5	               7	           10	         16
정수 n이 매개변수로 주어질 때, n을 3x 마을에서 사용하는 숫자로 바꿔 return하도록 solution 함수를 완성해주세요.
'''
list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)),range(101)))[15-1]


25

In [ ]:
def solution(num):
    return list(filter(lambda x: (x % 3 != 0) and ('3' not in str(x)),range(10000)))[num-1]

solution(33)

64

In [ ]:
def solution(num):
    l = []
    for i in range(1000):
        if i % 3 != 0:
            l.append(i)
        elif '3' not in str(i):
            l.append(i)
    print(l)

solution(15)

[0, 1, 2, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31, 32, 34, 35, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 124, 125, 126, 127, 128, 129, 130, 131, 133, 134, 136, 137, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 232, 233, 235, 2

In [ ]:
# 문제 9 진료순서 정하기
'''
외과의사 머쓱이는 응급실에 온 환자의 응급도를
기준으로 진료 순서를 정하려고 합니다.
정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로
진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.
제한사항
중복된 원소는 없습니다.
1 ≤ emergency의 길이 ≤ 10
1 ≤ emergency의 원소 ≤ 100
'''
# emergency	     result
# [3, 76, 24]	[3, 1, 2]

def solution(emergency):
    sorted_emergency = sorted(emergency, reverse = True)
    return [sorted_emergency.index(i) + 1 for i in emergency]

solution([3, 76, 24] )

[3, 1, 2]

In [ ]:
emergency = [3, 76, 24]

sorted_emergency = sorted(emergency, reverse = True)
sorted_emergency

[sorted_emergency.index(i) + 1 for i in emergency]

[3, 1, 2]

In [ ]:
data = ['제주', '경기', '전주'] # ['064', '031', '063']
data2 = {
    '제주': '064',
    '경기': '031',
    '전주': '063'
}

[data2[i] for i in data]

['064', '031', '063']

In [ ]:
# 문제 10 가까운 수
# [3, 10, 28, 30, 12] => [17, 10, 8, 10, 8]
# [3, 10, 28, 30, 12] => [(17, 3), (10, 10), (8, 28), (10, 30), (8, 12)]
# 원하는 숫자: 20
# result: 28

array = [3, 10, 28, 30, 12]
n = 20

28 - 20 == 8
12 - 20 == -8

20 - 28 == -8
20 - 12 == 8

sorted(array, key=lambda x:(abs(x-n), x))[0]
sorted(array, key=lambda x:(abs(x-n), n-x))[0] # 팁, n-x이거나 x-n 2개 중에 하나입니다.

28

In [ ]:
def solution(array, n):
    return sorted(array, key=lambda x:(abs(x-n), x))[0]

solution([3, 10, 28, 30, 12], 20)

12

## k의 개수

링크: https://school.programmers.co.kr/learn/courses/30/lessons/120887

In [ ]:
# i    j    k
# 1    13    1

i = 1
j = 13
k = 1

str(list(range(i, j+1)))
'[1, 2, 3]'.count(',')

2

In [ ]:
a = 10
b = 20

# swap

temp = a
a = b
b = temp

# python에서 사용하는 swap

a = 10
b = 20
a, b = b, a
a, b

(20, 10)

In [ ]:
def solution(i, j, k):
    return str(list(range(i, j+1))).count(str(k))

In [ ]:
i = 1
j = 13
k = 1

count = 0
for temp in range(i, j):
    count += str(temp).count(str(k))

count

5

강사 출제 문제

In [ ]:
# 각 선분이 있는 곳에 총 길이 합을 구하라
# [[0, 5], [3, 5], [7, 10]]

선 = [False] * 10
선

[False, False, False, False, False, False, False, False, False, False]

In [ ]:
for i  in range(0, 5):
    선[i] = True

선

[True, True, True, True, True, False, False, False, False, False]

In [ ]:
for i  in range(3, 5):
    선[i] = True

선

[True, True, True, True, True, False, False, False, False, False]

In [ ]:
for i  in range(7, 10):
    선[i] = True

선

[True, True, True, True, True, False, False, True, True, True]

In [ ]:
sum(선)

8

In [ ]:
# 에라토스테스트의 체 => 소수판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
소수 = [True] * 120
소수[0] = 소수[1] = False

소수

[False,
 False,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True,
 True]

In [ ]:
a = 10;b = 10
a, b

(10, 10)

In [ ]:
# 에라토스테스트의 체 => 소수판별 => 이것을 알고리즘 문제로 내는 것은 저는 반대
소수 = [True] * 120
소수[0] = 소수[1] = False

for i in range(4, 120, 2):
    소수[i] = False

for i in range(6, 120, 3):
    소수[i] = False

# for i in range(4, 120, 4): # 2의 배수에 속하기 때문에 4의 배수는 할 필요가 없습니다.
#     소수[i] = False

...

# https://nahwasa.com/entry/%EC%97%90%EB%9D%BC%ED%86%A0%EC%8A%A4%ED%85%8C%EB%84%A4%EC%8A%A4%EC%9D%98-%EC%B2%B4-%ED%98%B9%EC%9D%80-%EC%86%8C%EC%88%98%ED%8C%90%EC%A0%95-%EC%8B%9C-%EC%A0%9C%EA%B3%B1%EA%B7%BC-%EA%B9%8C%EC%A7%80%EB%A7%8C-%ED%99%95%EC%9D%B8%ED%95%98%EB%A9%B4-%EB%90%98%EB%8A%94-%EC%9D%B4%EC%9C%A0

Ellipsis

In [ ]:
# 행렬의 연산과 같은 것은 np를 사용하시면 쉽고 빠르게 풀 수 있습니다.
import numpy as np

x = np.array([1, 2, 3])
x * 2

array([2, 4, 6])

In [ ]:
s = [[1, 3, 5], [7, 9, 11], [13, 15, 17]]
s = np.array(s)
행, 렬 = np.where(s == 7)
행

array([1])

In [ ]:
# 지뢰찾기
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

x = np.array(x)
np.where(x == 1)

(array([0, 1, 2]), array([1, 1, 3]))

In [ ]:
x = [[0, 1, 0, 0],
     [0, 1, 0, 0],
     [0, 0, 0, 1]]

s = 0
for i in x:
    s += i.count(1)

s

3

In [ ]:
x = [[0, 5, 2, 0],
     [0, 7, 0, 6],
     [0, 1, 3, 5]]

x = np.array(x)
x > 3

array([[False,  True, False, False],
       [False,  True, False,  True],
       [False, False, False,  True]])