# 1. 시퀀스 자료형

In [ ]:
# 1.1 인덱싱

      #(-)54321
         #01234
example ='abcde'
print(example[0])
print(example[-5])

a
a


In [ ]:
# 1.2 슬라이싱

example ='abcde'
print(example[1:4])
print(example[-4:-1])

bcd
bcd


In [ ]:
# 1.3 특정항목 포함 여부

example ='abcde'
print('a' in example)
print(example in 'a') # 순서를 맞춰야 함!
print('z' in example)
print('z' not in example)

True
False
False
True


In [ ]:
# 1.4 연결 및 반복

example1 ='abcde'
example2 ='fg'
print(example1 + example2)
print(example1*3)

abcdefg
abcdeabcdeabcde


In [ ]:
# 1.5 내장함수

example = 'abcde'
print(len(example))  # 출력: 5
print(min(example))  # 출력: a
print(max(example))  # 출력: e

5
a
e


# 2. 패킹

In [ ]:
# 2.1 튜플 패킹

packed_tuple = 1, 2, 3, 4
print(packed_tuple)  # 출력: (1, 2, 3, 4)

(1, 2, 3, 4)


In [ ]:
# 2.2 언패킹

# 튜플 패킹
packed_tuple = 1, 2, 3, 4
print(packed_tuple)


(1, 2, 3, 4)


In [ ]:
# 튜플 언패킹
a, b, c, d = packed_tuple
print(a)  # 출력: 1
print(b)  # 출력: 2
print(c)  # 출력: 3
print(d)  # 출력: 4

1
2
3
4


In [ ]:
# 다양한 패킹/언패킹
# range는 0 에서부터 n-1만큼 숫자를 생성되는 함수
a, b, c = range(3)
print(range(3))
print(a,b,c)

range(0, 3)
0 1 2


In [ ]:
# 별표(*)를 이용한 언패킹
first, *middle, last = [1, 2, 3, 4, 5]
print(first)
print(middle)
print(last)

1
[2, 3, 4]
5


# 2.리스트

In [ ]:
# 리스트의 중요성

x1 = 100
x2 = 200
x3 = 300

x = [100, 200, 300]

In [ ]:
#리스트의 장점 : 여러가지 자료형을 넣을 수 있다.

z = [1, 'apple', 2.5, ['a', 'b'], (1, 2)]
print(z[0])
print(z[1])

1
apple


In [ ]:
z = [
		1,
		'apple',
		2.5,
		['a', 'b'],
		(1, 2)
]
print(z[3])

['a', 'b']


In [ ]:
# 2.2 리스트 값 수정

a = [1, 2, 3, 4, 5]
a[0] = 10000   # 리스트 값 수정
print(a)

[10000, 2, 3, 4, 5]


In [ ]:
# 문자열른 변경할 수 없다.
s = 'licat'
print(s[0])
s[0] = k

l


NameError: ignored

In [ ]:
# 2.3 다차원 리스트

b = [[10, 20, 30], [1, 2, 3]]
print(b)
print(b[1])
print(b[0])
print(b[0][2]) # 0번째 리스트의 2번째 값

[[10, 20, 30], [1, 2, 3]]
[1, 2, 3]
[10, 20, 30]
30


In [ ]:
b[0][2] = 5000
print(b[0], b[1])

[10, 20, 5000] [1, 2, 3]


In [ ]:
# 리스트의 덧셈_더해서 한 리스트로 생성

a = [1, 2, 3, 4, 5]
b = [6, 7, 8]

print(a + b) # 출력: [1, 2, 3, 4, 5, 6, 7, 8]

# numpy 는 후추 학습 예정
import numpy as np

l = [1, 2, 3]
print(type(l))
l = np.array(l)
print(l)
print(type(l))
print(l * 3)
print(l + l)
# 너무 당연하게 요소를 붙이는 것이다라고 생각하지 않으셨으면 좋겠습니다

[1, 2, 3, 4, 5, 6, 7, 8]
<class 'list'>
[1 2 3]
<class 'numpy.ndarray'>
[3 6 9]
[2 4 6]


In [ ]:
# 슬라이실 실습

l = [1, 2, 3, 4, 5]
print(l[:]) # 전체 출력
print(l[::-1]) # 역순 출력
print(l[::2]) # 2개씩 건너띄어서 출력
print(l[0:4][::-1]) # 0~4 까지 출력 후 역순 출


[1, 2, 3, 4, 5]
[5, 4, 3, 2, 1]
[1, 3, 5]
[4, 3, 2, 1]
